name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        coverage manage.py test
        coverage report
        coverage json -o coverage.json
        actual_coverage=$(jq ".totals.percent_covered_display"  coverage.json | cut -d '"' -f 2)
        if [ $actual_coverage -lt $RATE ]
        then
        echo "The acutual code coverge $actual_coverage is lower than expect coverage $RATE"
        exit 1
        fi
